name: Deploy to Preview Channel

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm i
    - uses: actions/checkout@v2
    - name: Run ESLint
      run: npm run lint-q
    - uses: actions/checkout@v2
    - name: Build the Application
      run: npm run build
    - uses: FirebaseExtended/action-hosting-deploy@v0
    - name: Deploy to Preview Channel
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_APP }}"
        expires: 30d
        projectId: aperidesarena
